[workspace]
members = [
    "monitor",
    # --- Common Modules ---
    "common/crypto",
    "common/network",
    "common/storage",
    "common/config",
    "common/keystore",
    # --- Core: Node, VM, Executor ---
    "core/node",
    "core/mempool",
    "core/executor",
    "core/vm_move",
    "core/cli",
    "core/move_compiler_tool",
    "core/genesis-tool",

    # --- Consensus & Account ---
    "consensus/consensus",
    "consensus/blockchain",
    "consensus/account",
    "consensus/aa",
    
    # --- Chain Synchronization ---
    "sync",
    
    # --- Data Availability ---
    "da",
    
    # --- Governance ---
    "governance/governance",
    
    # --- DePIN, Bridge, Oracle ---
    "depin/bridge-rust",
    "depin/btc-bridge",
    
    # --- Tools ---
    "indexer",
    "bench-tps", "utils/derive_keys",
]

resolver = "2"
