import argparse
import time
import json
import requests
import sys
import hashlib

# Requires: pip install requests pynacl
try:
    import nacl.signing
    import nacl.encoding
except ImportError:
    print("❌ Missing dependency 'pynacl'. Please run: pip install pynacl requests")
    sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="AINCORE Universal Miner Client")
    parser.add_argument("--node", default="http://127.0.0.1:8001/rpc", help="Node RPC URL")
    parser.add_argument("--device", required=True, help="Device ID (e.g. Phone-1)")
    parser.add_argument("--quality", type=int, default=95, help="Simulated Breath Quality (0-100)")
    parser.add_argument("--keyfile", default="data_1/node_identity.key", help="Path to Private Key Hex")
    
    args = parser.parse_args()

    # Load Key
    try:
        # Try reading as binary first
        with open(args.keyfile, 'rb') as f:
            raw_data = f.read()
            
        # Heuristic: If size is 32 or 64 bytes exactly, it's likely binary
        # If size is 64 chars or 128 chars (hex string), it might be text
        # Key generated by simulate_cluster.sh is binary (xxd -r -p)
        
        priv_bytes = raw_data.strip() # Binary strip?
        if len(priv_bytes) == 32:
            seed_bytes = priv_bytes
        elif len(priv_bytes) == 64:
            seed_bytes = priv_bytes[:32] # First 32 bytes usually seed
        else:
            # Maybe it is hex string?
            try:
                text_data = raw_data.decode('utf-8').strip()
                seed_bytes = bytes.fromhex(text_data[:64])
            except:
                print(f"❌ Key format unknown. Size: {len(raw_data)} bytes.")
                sys.exit(1)

        signing_key = nacl.signing.SigningKey(seed_bytes)
        verify_key = signing_key.verify_key
        pub_hex = verify_key.encode(encoder=nacl.encoding.HexEncoder).decode('utf-8')
        address = hashlib.sha256(verify_key.encode()).digest()[:16].hex()
    except Exception as e:
        print(f"❌ Key error: {e}")
        sys.exit(1)

    print(f"👤 Miner Address: {address}")
    print(f"📡 Connecting to Node: {args.node}")

    # 1. Get Sequence Number
    seq_num = 0
    try:
        response = requests.post(args.node, json={
            "jsonrpc": "2.0",
            "method": "aincore_getBalance",
            "params": [address],
            "id": 1
        })
        res = response.json()
        if 'result' in res and res['result']:
            # Parse 'data' bytes... cumbersome in Python without struct definition
            # Let's trust the sequence number if we can extract it, 
            # Or use a dedicated API.
            # Workaround: Since parsing AccountData bytes is hard in pure python without schemas,
            # We MIGHT assume Seq 0 if new, or basic extraction.
            # IMPROVEMENT: Add 'aincore_getAccountSeq' RPC?
            # Or rely on CLI?
            # For this demo script, let's assume valid key implies existing account if balance > 0.
            # But extracting seq num from raw bytes is risky.
            # Let's accept 0 and let it fail?
            # Actually, `aincore_getBalance` returns the Account Object.
            # The `data` field is `Vec<u8>`.
            # AccountData: [8 bytes Balance][8 bytes Seq][8 bytes BTC][String Pubkey...]
            # Rust serialization adds length prefix?
            
            data = res['result']['data']
            # Simple heuristic for AccountData (bcs/serde):
            # Balance (u64) = bytes[0..8]
            # Seq (u64) = bytes[8..16]
            # Assuming standard layout (no serde metadata overhead?)
            # Serde JSON to Vec<u8> is just JSON bytes!
            # Wait. `serde_json::to_vec` produces JSON UTF-8 Bytes!
            # So `data` IS A JSON BUFFER [123, 34, ...].
            # WE CAN PARSE IT!
            
            data_str = bytes(data).decode('utf-8')
            acc_json = json.loads(data_str)
            seq_num = acc_json.get('sequence_number', 0)
            
            print(f"✅ Synced Sequence Number: {seq_num}")

    except Exception as e:
        print(f"⚠️ Failed to fetch sequence: {e}. Defaulting to 0.")

    # 2. Build Transaction
    payload = f"submit_proof:{args.device}:{args.quality}"
    message = f"AINCORE-MAINNET-1:{address}:{payload}:{seq_num}"
    
    signed = signing_key.sign(message.encode('utf-8'))
    signature_hex =signed.signature.hex()

    tx = {
        "chain_id": "AINCORE-MAINNET-1",
        "sender": address,
        "public_key": pub_hex, 
        "input_objects": [],
        "payload": payload,
        "gas_limit": 5000,
        "gas_price": 1,
        "sequence_number": seq_num,
        "signature": signature_hex
    }
    
    print(f"🚀 Sending Proof: {payload}")
    
    # 3. Send
    try:
        resp = requests.post(args.node, json={
            "jsonrpc": "2.0",
            "method": "aincore_sendTransaction",
            "params": [json.dumps(tx)], # Expects string
            "id": 2
        })
        print(f"✅ Response: {resp.text}")
    except Exception as e:
        print(f"❌ Send Failed: {e}")

if __name__ == "__main__":
    main()
