[package]
name = "move_compiler_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
move-compiler = { git = "https://github.com/move-language/move", branch = "aptos-v1.3.0" }
move-core-types = { git = "https://github.com/move-language/move", branch = "aptos-v1.3.0" }
move-symbol-pool = { git = "https://github.com/move-language/move", branch = "aptos-v1.3.0" }
hex = "0.4"


